(function(){
  const C=window.PMPCore;
  const DEMO=window.PMP_DEMO_ITEMS.map(C.normalizeItem);
  const PROD=null;
  const state={view:'home',bank:[],source:'',practice:null,sim:null,lastResult:null,settings:{feedback:'immediate'}};
  const el=id=>document.getElementById(id);

  function save(){
    localStorage.setItem('pmpv6-state',JSON.stringify({bank:state.bank,source:state.source,practice:state.practice,sim:state.sim,settings:state.settings}));
  }
  function load(){
    try{
      const s=JSON.parse(localStorage.getItem('pmpv6-state')||'null');
      if(s){state.bank=s.bank||[];state.source=s.source||'';state.practice=s.practice||null;state.sim=s.sim||null;state.settings=s.settings||state.settings;}
    }catch{}
    if(!state.bank.length){
      if(PROD&&Array.isArray(PROD.items)&&PROD.items.length===600){state.bank=PROD.items.map(C.normalizeItem);state.source='Controlled 600-item draft import (bundled)';}
      else{state.bank=DEMO;state.source='DEMO ONLY';}
    }
  }
  function getProgress(){try{return JSON.parse(localStorage.getItem('pmpv6-progress')||'{"attempts":0,"correct":0,"byDomain":{}}')}catch{return{attempts:0,correct:0,byDomain:{}}}}
  function setProgress(p){localStorage.setItem('pmpv6-progress',JSON.stringify(p))}
  function record(items,responses){const p=getProgress();items.forEach((it,i)=>{if(responses[i]==null)return;p.attempts++;const ok=C.score(it,responses[i]);if(ok)p.correct++;p.byDomain[it.Domain]=p.byDomain[it.Domain]||{a:0,c:0};p.byDomain[it.Domain].a++;if(ok)p.byDomain[it.Domain].c++;});setProgress(p)}
  function nav(){document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.onclick=()=>{state.view=b.dataset.view;render()};})}
  function fmtTime(sec){sec=Math.max(0,sec|0);return `${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
  function counts(bank){return C.validateItems(bank).counts}
  function blueprintVariance(bank){const c=counts(bank),d=c.domain,a=c.approach;const non=(a['Adaptive/Agile']||0)+(a.Hybrid||0);return {People:(d.People||0)-198,Process:(d.Process||0)-246,'Business Environment':(d['Business Environment']||0)-156,Predictive:(a.Predictive||0)-240,NonPredictive:non-360}}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function stemKey(it){return String(it['Stem / Prompt']||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
  function uniqueItems(bank){const ids=new Set(),stems=new Set(),out=[];for(const it of bank){const id=String(it['Item ID']||'').trim(),sk=stemKey(it);if(id&&ids.has(id))continue;if(sk&&stems.has(sk))continue;if(id)ids.add(id);if(sk)stems.add(sk);out.push(it)}return out}
  function render(){nav();const main=el('main');if(state.view==='home')home(main);else if(state.view==='practice')practiceSetup(main);else if(state.view==='simulation')simulation(main);else if(state.view==='progress')progress(main);else settings(main)}
  function home(m){const c=counts(state.bank),v=blueprintVariance(state.bank),isDemo=state.source.includes('DEMO');m.innerHTML=`<div class="stack"><div><h1>PMP Training v6.0 Simulator</h1><p class="muted">Executable study simulator for independently authored draft practice content.</p></div><div class="banner ${isDemo?'':'good'}"><strong>Active data:</strong> ${esc(state.source)}. ${isDemo?'Demo data is not the production bank.':'Items remain draft and are not SME-validated or psychometrically calibrated.'}</div><div class="grid cols-3"><div class="card"><div class="muted">Active items</div><div class="kpi">${state.bank.length}</div></div><div class="card"><div class="muted">Predictive</div><div class="kpi">${c.approach.Predictive||0}</div></div><div class="card"><div class="muted">Adaptive + Hybrid</div><div class="kpi">${(c.approach['Adaptive/Agile']||0)+(c.approach.Hybrid||0)}</div></div></div>${!isDemo&&Object.values(v).some(x=>x!==0)?`<div class="banner"><strong>Blueprint reconciliation warning:</strong> imported item metadata does not exactly match the control targets. Diagnostics reports the actual counts; the simulator does not rewrite metadata.</div>`:''}<div class="grid cols-2"><div class="card"><h2>Practice</h2><p>Filter the bank and work with immediate or end-of-set feedback.</p><button class="btn" id="goPractice">Start practice</button></div><div class="card"><h2>Full Simulation</h2><p>180 questions, 240 minutes, autosave, flags, and review navigation.</p><button class="btn" id="goSim" ${state.bank.length<180?'disabled':''}>${state.sim?'Resume simulation':'Start simulation'}</button></div></div><div class="card"><h2>Domain counts</h2><div class="row">${Object.entries(c.domain).map(([k,n])=>`<span class="pill">${esc(k)}: ${n}</span>`).join('')}</div></div></div>`;el('goPractice').onclick=()=>{state.view='practice';render()};el('goSim').onclick=()=>{state.view='simulation';render()}}
  function filters(){const uniq=(k)=>[...new Set(state.bank.map(x=>x[k]).filter(Boolean))].sort();return {domains:uniq('Domain'),approaches:uniq('Approach'),formats:uniq('Format')}}
  function filteredPracticePool(){const pd=el('pd')?.value||'',pa=el('pa')?.value||'',pf=el('pf')?.value||'';return uniqueItems(state.bank.filter(x=>(!pd||x.Domain===pd)&&(!pa||x.Approach===pa)&&(!pf||x.Format===pf)))}
  function practiceSetup(m){if(state.practice&&state.practice.running)return renderRunner(m,state.practice,false);const f=filters();m.innerHTML=`<h1>Practice</h1><div class="card stack"><div class="grid cols-2"><div class="field"><label for="pd">Domain</label><select id="pd"><option value="">All</option>${f.domains.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label for="pa">Approach</label><select id="pa"><option value="">All</option>${f.approaches.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label for="pf">Format</label><select id="pf"><option value="">All</option>${f.formats.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label for="pc">Question count</label><input id="pc" type="number" min="1" max="100" value="20"></div><div class="field"><label for="fb">Feedback</label><select id="fb"><option value="immediate">Immediate</option><option value="end">End of set</option></select></div></div><div id="poolStatus" class="banner good" aria-live="polite"></div><button class="btn" id="startP">Start practice set</button></div>`;const updatePool=()=>{const pool=filteredPracticePool();const requested=Math.max(1,Number(el('pc').value)||20);el('poolStatus').textContent=`${pool.length} item(s) match these filters. The set will use ${Math.min(requested,pool.length)} item(s).`};['pd','pa','pf','pc'].forEach(id=>el(id).addEventListener('change',updatePool));el('pc').addEventListener('input',updatePool);updatePool();el('startP').onclick=()=>{let pool=filteredPracticePool();if(!pool.length)return alert('No items match those filters.');const requested=Math.max(1,Number(el('pc').value)||20);pool=shuffle(pool).slice(0,Math.min(requested,pool.length));state.practice={running:true,items:pool,index:0,responses:{},flags:{},feedback:el('fb').value,submitted:{}};save();render()}}
  function itemUI(it,response,readonly=false){const opts=['A','B','C','D'];let body='';if(it.Format==='multiple_response'){const selected=new Set(response||[]);body=opts.map(k=>`<label class="option"><input type="checkbox" data-answer="${k}" ${selected.has(k)?'checked':''} ${readonly?'disabled':''}><span><strong>${k}.</strong> ${esc(it[k])}</span></label>`).join('')}else if(it.Format==='ordering'){const order=Array.isArray(response)&&response.length?response:opts;body=`<div class="sort-list">${order.map((k,i)=>`<div class="sort-item"><span><strong>${k}.</strong> ${esc(it[k])}</span>${readonly?'':`<span><button class="btn ghost" data-up="${i}" aria-label="Move ${k} up">↑</button> <button class="btn ghost" data-down="${i}" aria-label="Move ${k} down">↓</button></span>`}</div>`).join('')}</div>`}else if(it.Format==='matching'){const r=response||{};body=`<div class="stack">${['1','2','3','4'].map(n=>`<div class="match-row"><div>Situation ${n}</div><select data-match="${n}" ${readonly?'disabled':''}><option value="">Select</option>${opts.map(k=>`<option value="${k}" ${r[n]===k?'selected':''}>${k}. ${esc(it[k])}</option>`).join('')}</select></div>`).join('')}</div>`}else{body=opts.map(k=>`<label class="option"><input type="radio" name="ans" data-answer="${k}" ${response===k?'checked':''} ${readonly?'disabled':''}><span><strong>${k}.</strong> ${esc(it[k])}</span></label>`).join('')}const artifact=(it.Format==='graphic_interpretation'||it.Format==='calculation_interpretation')?`<div class="artifact"><strong>Accessible data/text equivalent</strong><div>${esc(it['Artifact Text Equivalent']||it['Stem / Prompt']||'No text equivalent supplied.')}</div></div>`:'';return `${artifact}<div class="question">${esc(it['Stem / Prompt'])}</div><div class="stack">${body}</div>`}
  function isAutoSubmitFormat(it){return ['single_response','calculation_interpretation','graphic_interpretation'].includes(it.Format)}
  function bindAnswer(session,it,isSim){document.querySelectorAll('[data-answer]').forEach(x=>x.onchange=()=>{if(it.Format==='multiple_response')session.responses[session.index]=[...document.querySelectorAll('[data-answer]:checked')].map(y=>y.dataset.answer);else session.responses[session.index]=x.dataset.answer;if(!isSim&&session.feedback==='immediate'&&isAutoSubmitFormat(it))session.submitted[session.index]=true;save();if(!isSim&&session.feedback==='immediate'&&isAutoSubmitFormat(it))render()});document.querySelectorAll('[data-match]').forEach(x=>x.onchange=()=>{session.responses[session.index]=session.responses[session.index]||{};session.responses[session.index][x.dataset.match]=x.value;save()});document.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>moveOrder(session,Number(b.dataset.up),-1));document.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>moveOrder(session,Number(b.dataset.down),1))}
  function moveOrder(s,i,d){let arr=s.responses[s.index]||['A','B','C','D'];arr=[...arr];const j=i+d;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];s.responses[s.index]=arr;save();render()}
  function ensureResponseForCheck(s,it){if(s.responses[s.index]!=null)return;if(it.Format==='ordering')s.responses[s.index]=['A','B','C','D'];else if(it.Format==='multiple_response')s.responses[s.index]=[];else if(it.Format==='matching')s.responses[s.index]={}}
  function needsCheckButton(s,it,isSim){return !isSim&&s.feedback==='immediate'&&!isAutoSubmitFormat(it)&&!s.submitted[s.index]}
  function renderRunner(m,s,isSim){const it=s.items[s.index],resp=s.responses[s.index];const show=!isSim&&((s.feedback==='immediate'&&s.submitted[s.index])||s.finished);const lockAnswer=!isSim&&s.feedback==='immediate'&&Boolean(s.submitted[s.index]);const checkButton=needsCheckButton(s,it,isSim)?`<button class="btn" id="checkAnswer">Check answer</button>`:'';m.innerHTML=`<div class="row runner-header" style="justify-content:space-between"><div><h1>${isSim?'Full Simulation':'Practice'}</h1><div class="muted">Question ${s.index+1} of ${s.items.length}</div></div>${isSim?`<div class="row"><div class="timer" id="timer">${fmtTime(remaining(s))}</div><button class="btn danger" id="submitExamTop">Submit Exam</button></div>`:''}</div><div class="progressbar"><div style="width:${((s.index+1)/s.items.length)*100}%"></div></div><div class="grid cols-2 runner-layout" style="grid-template-columns:minmax(0,1fr) 280px"><div class="card stack">${itemUI(it,resp,lockAnswer)}${show?feedback(it,resp):''}${checkButton}<div class="row runner-actions"><button class="btn secondary" id="prev" ${s.index===0?'disabled':''}>Previous</button><button class="btn secondary" id="flag">${s.flags[s.index]?'Unflag':'Flag for review'}</button><button class="btn" id="next">${s.index===s.items.length-1?(isSim?'Review / Submit':'Finish practice'):'Next'}</button>${isSim?`<button class="btn danger" id="submitExamBottom">Submit Exam</button>`:''}</div></div><div class="card"><h3>Navigator</h3><div class="navigator">${s.items.map((_,i)=>`<button class="navq ${s.responses[i]!=null?'answered':''} ${s.flags[i]?'flagged':''}" data-q="${i}" aria-label="Question ${i+1}${s.responses[i]!=null?', answered':''}${s.flags[i]?', flagged':''}">${i+1}</button>`).join('')}</div></div></div>`;bindAnswer(s,it,isSim);document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{s.index=Number(b.dataset.q);save();render()});el('prev').onclick=()=>{s.index--;save();render()};el('flag').onclick=()=>{s.flags[s.index]=!s.flags[s.index];save();render()};if(el('checkAnswer'))el('checkAnswer').onclick=()=>{ensureResponseForCheck(s,it);s.submitted[s.index]=true;save();render()};el('next').onclick=()=>{if(s.index<s.items.length-1){s.index++;save();render()}else if(isSim)finishSession(s,true);else finishSession(s,false)};if(isSim){const submit=()=>finishSession(s,true);el('submitExamTop').onclick=submit;el('submitExamBottom').onclick=submit;startTimer(s)}}
  function feedback(it,r){const ok=C.score(it,r);return `<div class="feedback" role="status"><div class="banner ${ok?'good':'bad'}"><strong>${ok?'Correct':'Incorrect — review this item'}</strong></div><p><strong>Correct key:</strong> ${esc(it['Correct Key'])}</p><p>${esc(it.Rationale||'')}</p><p><strong>Decision rule:</strong> ${esc(it['Decision Rule']||'')}</p></div>`}
  function finishSession(s,isSim){if(isSim&&!confirm('Submit the full simulation now? You will not be able to resume this attempt.'))return;s.finished=true;s.running=false;record(s.items,s.responses);const correct=s.items.reduce((n,it,i)=>n+(C.score(it,s.responses[i])?1:0),0);state.lastResult={items:s.items,responses:s.responses,correct,total:s.items.length,isSim};if(isSim)state.sim=null;else state.practice=null;save();state.view='progress';render()}
  let timerHandle=null;function remaining(s){return Math.max(0,Math.floor((s.endsAt-Date.now())/1000))}function startTimer(s){clearInterval(timerHandle);timerHandle=setInterval(()=>{const t=el('timer');if(!t)return;if(remaining(s)<=0){clearInterval(timerHandle);finishSession(s,true);return}t.textContent=fmtTime(remaining(s));save()},1000)}
  function simulation(m){if(state.sim&&state.sim.running)return renderRunner(m,state.sim,true);const available=uniqueItems(state.bank).length;m.innerHTML=`<h1>Full Simulation</h1><div class="card stack"><div class="banner"><strong>180 questions • 240 minutes.</strong> Once started, there is no pause control. Progress is autosaved in this browser and resumes after refresh.</div><p>Active bank: ${esc(state.source)} (${state.bank.length} items; ${available} unique IDs/stems available)</p><button class="btn" id="startS" ${available<180?'disabled':''}>Start 180-question simulation</button></div>`;el('startS').onclick=()=>{if(!confirm('Start a 240-minute simulation now?'))return;const items=shuffle(uniqueItems(state.bank)).slice(0,180);state.sim={running:true,items,index:0,responses:{},flags:{},startedAt:Date.now(),endsAt:Date.now()+240*60*1000};save();render()}}
  function progress(m){const p=getProgress(),pct=p.attempts?Math.round(p.correct/p.attempts*100):0;let result='';if(state.lastResult){const r=state.lastResult;result=`<div class="card"><h2>Latest result</h2><div class="kpi">${r.correct}/${r.total}</div><p>${Math.round(r.correct/r.total*100)}% correct</p><details><summary>Review items</summary><div class="stack">${r.items.map((it,i)=>`<div class="card"><div class="small muted">${esc(it['Item ID'])} • ${esc(it.Domain)} • ${esc(it.Format)}</div>${itemUI(it,r.responses[i],true)}${feedback(it,r.responses[i])}</div>`).join('')}</div></details></div>`}m.innerHTML=`<h1>Progress</h1><div class="grid cols-3"><div class="card"><div class="muted">Attempts</div><div class="kpi">${p.attempts}</div></div><div class="card"><div class="muted">Correct</div><div class="kpi">${p.correct}</div></div><div class="card"><div class="muted">Accuracy</div><div class="kpi">${pct}%</div></div></div>${result}<div class="card"><h2>By domain</h2><div class="tablewrap"><table><thead><tr><th>Domain</th><th>Attempts</th><th>Accuracy</th></tr></thead><tbody>${Object.entries(p.byDomain).map(([d,x])=>`<tr><td>${esc(d)}</td><td>${x.a}</td><td>${Math.round(x.c/x.a*100)}%</td></tr>`).join('')}</tbody></table></div></div>`}
  function settings(m){const val=C.validateItems(state.bank),v=blueprintVariance(state.bank);m.innerHTML=`<h1>Settings & Import Diagnostics</h1><div class="card stack reset-controls" id="resetControls"><h2>Reset & Clear Controls</h2><p class="small muted">These controls affect only this browser. They do not change the private source bank in Google Drive.</p><div class="row"><button class="btn danger" id="clear">Clear progress</button><button class="btn secondary" id="resetPractice">Reset current practice</button><button class="btn secondary" id="clearSim">Clear saved simulation</button><button class="btn secondary" id="demo">Reset bank to DEMO ONLY</button></div></div><div class="grid cols-2"><div class="card stack"><h2>Data source</h2><p><strong>${esc(state.source)}</strong></p><p class="small muted">Production questions are intentionally not stored in this public repository. Use the JSON/CSV import control to load the controlled bank from your private source.</p></div><div class="card stack"><h2>Import JSON or CSV</h2><input type="file" id="file" accept=".json,.csv,application/json,text/csv"><div id="importStatus" class="small muted">Validation runs before data is committed.</div></div></div><div class="card"><h2>Current diagnostics</h2>${diagHTML(val,v)}</div>`;el('demo').onclick=()=>{if(confirm('Reset the active bank to DEMO ONLY?')){state.bank=DEMO;state.source='DEMO ONLY';state.practice=null;state.sim=null;save();render()}};el('clear').onclick=()=>{if(confirm('Clear all saved progress?')){localStorage.removeItem('pmpv6-progress');state.lastResult=null;render()}};el('resetPractice').onclick=()=>{state.practice=null;save();alert('Current practice session cleared.')};el('clearSim').onclick=()=>{if(confirm('Clear the saved full simulation?')){state.sim=null;save();alert('Saved simulation cleared.')}};el('file').onchange=importFile}
  function diagHTML(val,v){const table=(obj)=>Object.entries(obj).map(([k,n])=>`<tr><td>${esc(k)}</td><td>${n}</td></tr>`).join('');return `${val.errors.length?`<div class="banner bad"><strong>${val.errors.length} validation error(s)</strong><ul>${val.errors.slice(0,12).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:`<div class="banner good"><strong>Schema validation passed</strong></div>`}${val.warnings.length?`<div class="banner"><strong>${val.warnings.length} warning(s)</strong><ul>${val.warnings.slice(0,8).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<div class="grid cols-3"><div><h3>Domains</h3><table>${table(val.counts.domain)}</table></div><div><h3>Approaches</h3><table>${table(val.counts.approach)}</table></div><div><h3>Formats</h3><table>${table(val.counts.format)}</table></div></div><h3>Blueprint variance from control targets</h3><table><thead><tr><th>Dimension</th><th>Variance</th></tr></thead><tbody>${Object.entries(v).map(([k,n])=>`<tr><td>${esc(k)}</td><td>${n>0?'+':''}${n}</td></tr>`).join('')}</tbody></table><p class="small muted">A nonzero value is reported, not automatically corrected. Metadata reconciliation belongs to controlled QA.</p>`}
  function importFile(e){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{let data;if(f.name.toLowerCase().endsWith('.csv'))data=C.parseCSV(reader.result);else data=JSON.parse(reader.result);const val=C.validateItems(data);el('importStatus').innerHTML=val.valid?`<div class="banner good">Valid import: ${val.items.length} items. <button class="btn" id="commit">Commit to local browser</button></div>`:`<div class="banner bad">Import blocked: ${val.errors.length} error(s).</div>`;if(val.valid)el('commit').onclick=()=>{state.bank=val.items;state.source=`Imported file: ${f.name}`;state.practice=null;state.sim=null;save();render()}}catch(err){el('importStatus').innerHTML=`<div class="banner bad">Could not parse file: ${esc(err.message)}</div>`}};reader.readAsText(f)}
  load();render();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
